#!/bin/bash
#Author YouTiao
#Source https://github.com/YouTiao233/mcsl
#GPL-3.0
echo ""
echo "+--------------------------------------------------+"
echo "| Manager for Minecraft-Server, Written by YouTiao |"
echo "+--------------------------------------------------+"
echo ""
#config
source /etc/mcsl.conf
Server="$2"
Command="$1"
import 
#DON'T edit the following line of code,unless you know how to edit!
#Core code 
case "$1" in
#START
 -start)
  if [ ! -d $start ]; then
   echo "ERROR!!! can't not find the server dir!"
  else
   if [ ! -f $start/$sh ]; then
    echo "ERROR!!! can't not find the "$start"!"
   else
    bash -c "cd "$start" && bash "$sh
    echo $Server" has start!"
   fi
  fi
 exit
 ;;
#LIST
 -list)
  echo "Online Servers:"
  screen -ls|grep -v There|grep -v Socket
  exit
 ;;
#RESTART
 -restart)
  if [ ! -d $start ]; then
   echo "ERROR!!! can't not find the server dir!"
  else
   if [ ! -f $start/$sh ]; then
    echo "ERROR!!! can't not find the "$start"!"
   else
    check=`screen -ls|grep $Server|wc -l` 
    if [ "$check" -gt "0" ]; then
     screen -S $Server -X quit
     bash -c "cd "$start" && bash "$sh
     echo $Server" has restart!"
    fi
   fi
  fi
  exit
 ;;
#STOP
 -stop)
  check=`screen -ls|grep $Server|wc -l` 
  if [ "$check" -gt "0" ]; then
   screen -S $Server -X quit
   echo $Server" has stop!"
  else
   echo "ERROR!!! can't not find the server! "
  fi
  exit
 ;;
#RETURN
 -return)
  check=`screen -ls|grep $Server|wc -l` 
  if [ "$check" -gt "0" ]; then
   screen -r $Server
  else
   echo "ERROR!!! can't not find the server! "
  fi
  exit
 ;
esac
